/**
 * Every word a founder or the team reads, in one place. The rules are in
 * docs/VOICE.md and the copy lint enforces them: no banned words, buttons
 * under 24 characters, no exclamation marks outside the reveal and the card,
 * no decorative quote marks. Choices among options are in docs/COPY_CHOICES.md.
 */

import type { ArchetypeId, FamilyId } from '@/lib/archetype'

export const families: Record<FamilyId, { name: string; line: string }> = {
  cartographer: { name: 'Cartographer', line: 'Understand it, then build it.' },
  alchemist: { name: 'Alchemist', line: 'Try it and find out.' },
  architect: { name: 'Architect', line: 'See the shape first.' },
}

export const archetypes: Record<
  ArchetypeId,
  { name: string; identity: string; strengths: [string, string]; blindSpot: string; loves: string }
> = {
  surveyor: {
    name: 'Surveyor',
    identity: 'You map the ground before you take a step.',
    strengths: [
      'You find the real question under the obvious one',
      'You turn a mess into a picture others can follow',
    ],
    blindSpot: 'The map can quietly become the work.',
    loves:
      'Problems tangled in information. Search, research, dashboards, AI that reads and explains.',
  },
  scout: {
    name: 'Scout',
    identity: "You'd rather ask 10 people than guess once.",
    strengths: [
      'You talk to people before you decide anything',
      'You notice what everyone else walks past',
    ],
    blindSpot: "You keep exploring when it's time to commit.",
    loves:
      'Problems you only understand by being there. Communities, voice, WhatsApp, quick prototypes.',
  },
  inventor: {
    name: 'Inventor',
    identity: 'You make the first version while others are still planning.',
    strengths: [
      'You have a working version before anyone else',
      "You're at home with tools that came out this month",
    ],
    blindSpot: 'Speed hides the reason it worked.',
    loves: 'AI agents, new models, creative and consumer tools.',
  },
  tinkerer: {
    name: 'Tinkerer',
    identity: 'You make it work today and make it good tomorrow.',
    strengths: [
      'You turn quick fixes into tools people rely on',
      'You improve things in small, safe steps',
    ],
    blindSpot: 'You can build before asking whether anyone needs it.',
    loves: 'Automation, integrations and the internal tools small businesses run on.',
  },
  strategist: {
    name: 'Strategist',
    identity: 'You see the whole board before your first move.',
    strengths: [
      'Your plans survive contact with reality',
      'You split work so a team can move at once',
    ],
    blindSpot: 'A shape drawn too early is the wrong shape.',
    loves: 'Operations for businesses, data models and full-stack products.',
  },
  builder: {
    name: 'Builder',
    identity: 'You make a plan, then prove it works.',
    strengths: ['You build structure with fast feedback', 'You finish what you start'],
    blindSpot: 'You can polish the plan longer than the problem deserves.',
    loves: 'Payments, platforms and anything with a hard technical edge.',
  },
}

/** The seven questions, in the founder's words. Scoring lives in lib/archetype.ts. */
export const trial: Record<string, { prompt: string; options: Record<string, string> }> = {
  'new-city': {
    prompt: 'You have 3 days in a new city. What do you do first?',
    options: { read: 'Read up before you go', walk: 'Walk out and see', plan: 'Plan all 3 days' },
  },
  'new-tool': {
    prompt: 'The last time you learned a new tool, what did you do first?',
    options: {
      read: 'Read how it worked',
      use: 'Played with it until it clicked',
      tutorial: 'Followed a tutorial',
    },
  },
  'first-prompt': {
    prompt: 'A messy task and an AI. What do you type first?',
    options: {
      everything: "Here's everything. What do you think?",
      steps: 'Break this into steps',
      explain: 'Explain this to me first',
    },
  },
  'in-a-team': {
    prompt: 'In a team of 4, what do you do without being asked?',
    options: {
      agree: "Get everyone agreeing on what we're building",
      rough: 'Make the first rough version',
      split: 'Split up who does what',
    },
  },
  'bad-instructions': {
    prompt: 'The instructions look wrong. What do you do?',
    options: { why: 'Work out why', own: 'Try your own way', follow: 'Follow them, then say so' },
  },
  'it-broke': {
    prompt: "It worked yesterday. Today it doesn't. What do you do?",
    options: {
      changed: 'Find what changed',
      tweak: 'Change things until it works',
      rollback: 'Go back to the version that worked',
    },
  },
  'better-way': {
    prompt: 'Halfway through, you see a better way. What now?',
    options: {
      finish: 'Finish this part, then decide',
      think: 'Stop and think it through',
      scrap: 'Scrap it and rebuild',
    },
  },
}

export const landing = {
  kicker: 'ForgeX',
  lineStart: "Don't start with an idea.",
  lineEm: 'Start with a problem.',
  sub: "Find one. Prove it's real. Then build.",
  enter: 'Enter',
  building: {
    title: "What they're building",
    lead: 'Who each founder is building for. Live links appear once the team has seen them work.',
    empty: 'Nobody has sent their research yet. Founders show up here once they do.',
    open: (name: string) => `Open ${name}'s profile`,
    live: 'Open the app',
  },
}

export const card = {
  number: (n: number, of: number) => `#${String(n).padStart(3, '0')} / ${of}`,
  unnumbered: 'ForgeX',
  original: 'Original',
  noArchetype: 'Archetype to come',
  building: 'Building',
  download: 'Download card',
  share: 'Share',
  shareText: (name: string) => `${name} on ForgeX`,
  footer: { brand: 'FORGEX', school: 'MESA SCHOOL OF BUSINESS' },
}

export const meta = {
  title: 'ForgeX',
  template: '%s · ForgeX',
  description:
    "Don't start with an idea. Start with a problem. Find one, prove it's real, then build.",
  brand: 'ForgeX home',
  pages: {
    signIn: 'Sign in',
    arrive: 'Arrive',
    archetype: 'Archetype',
    profile: 'Profile',
    challenge: 'The challenge',
    research: 'Your research',
    today: 'Today',
    plan: 'Your plan',
    stops: 'Stops',
    stop: (n: string) => `Stop ${n}`,
    messages: 'Messages',
    pod: 'Your pod',
    console: 'Console',
    consoleTemplate: '%s · Console',
    founders: 'Founders',
    bank: 'Bank',
    pods: 'Pods',
    setup: 'Setup check',
  },
}

export const notFound = {
  title: "This page isn't here.",
  lead: 'The link may be old, or have a typo.',
  home: 'Go to the start',
}

export const crashed = {
  title: "This page didn't load.",
  lead: 'Nothing you wrote is lost. Try again in a moment.',
  retry: 'Try again',
}

export const wall = {
  face: (first: string, archetype: string | null) => (archetype ? `${first}, ${archetype}` : first),
  label: 'The founders of ForgeX',
}

export const levels = {
  names: {
    arrive: 'Arrive',
    archetype: 'Archetype',
    profile: 'Profile',
    challenge: 'The challenge',
    research: 'Your research',
  },
  of: (at: number, of: number, name: string) => `Step ${at} of ${of}: ${name}`,
  card: 'Your founder card',
}

export const login = {
  title: 'Sign in',
  lead: 'Use your Mesa Google account.',
  google: 'Continue with Google',
  refused: {
    domain: "That's not a Mesa founder account. Sign in with your @forge27.mesaschool.co address.",
    roster: "This account isn't on the ForgeX roster. If it should be, message the Mesa team.",
    other: "Sign-in didn't finish. Try again in a moment.",
  },
  another: 'Use another account',
  mock: 'Mock sign-in',
  mockAs: (who: string) => `Sign in as ${who}`,
}

export const arrive = {
  hi: (first: string) => `Hi, ${first}.`,
  /** Two lines on purpose: the promise gets a line of its own. */
  lead: ['5 steps. By the last one,', "you'll know what to build."],
  steps: 'The 5 steps',
  path: [
    { name: 'Arrive', line: "You're here." },
    { name: 'Archetype', line: 'The kind of builder you are.' },
    { name: 'Profile', line: 'You, in your own words.' },
    { name: 'The challenge', line: 'One problem, for all 117 of you.' },
    { name: 'Your research', line: 'Find out where it really breaks.' },
  ],
  go: 'Find my archetype',
  numbering: 'Numbering your card',
}

export const archetypeFlow = {
  intro: {
    title: 'What kind of builder are you?',
    lead: '7 questions. Answer on instinct.',
    start: 'Find out',
    retakeTitle: 'One more go',
    retakeLead: 'Your new result replaces the old one. This is your only retake.',
  },
  question: (at: number, of: number) => `${at} of ${of}`,
  back: 'Back',
  placing: 'Working out your archetype',
  retry: 'Try again',
  error: "That didn't save. Your answers are still here. Try again.",
  reveal: {
    youAre: "You're a",
    exclaim: '!',
    h1: (family: string, kind: string) =>
      `Hackathon 1 placed you as a ${family}. More precisely, a ${kind}.`,
    strengths: 'Strengths',
    blindSpot: 'Blind spot',
    loves: 'Loves',
    keep: "That's me",
    next: 'Next: your profile',
    retake: 'Retake the quiz',
    retakeUsed: 'Retake used',
    cardTitle: 'Your founder card',
    cardLead: 'It fills in as you go, and takes its finish when you start building.',
  },
  portraitAlt: {
    cartographer: 'Cartographer, holding a compass, a map under one arm',
    alchemist: 'Alchemist, in goggles, holding a glowing flask',
    architect: 'Architect, in a visor, beside a glowing blueprint',
  },
}

export const profile = {
  heading: "This is you so far. Change anything that doesn't feel like you.",
  bio: {
    label: 'One line about you',
    placeholder: "I sell my mum's pickles on Instagram and want it to be a real business.",
    required: 'Add one line about you to carry on.',
    add: 'Add one line about you',
  },
  facts: {
    city: { label: 'Lives in', icon: '📍', placeholder: 'Pune' },
    languages: { label: 'Speaks', icon: '🗣️', placeholder: 'Marathi' },
    degree: { label: 'Studies', icon: '🎓', placeholder: 'BBA, Commerce and Management' },
  },
  goodAt: {
    label: 'Good at today',
    icon: '💪',
    placeholder: 'Cold calling',
    suggestions: [
      'Sales',
      'Research',
      'Writing',
      'Design',
      'Excel',
      'Video',
      'Coding',
      'Public speaking',
      'Operations',
    ],
  },
  wantToLearn: {
    label: 'Wants to learn',
    icon: '🌱',
    placeholder: 'Voice AI',
    suggestions: [
      'AI agents',
      'Voice AI',
      'Full-stack web',
      'Data',
      'Product design',
      'Growth marketing',
      'Mobile apps',
    ],
  },
  links: {
    label: 'Find me',
    icon: '🔗',
    github: 'GitHub',
    linkedin: 'LinkedIn',
    portfolio: 'Portfolio or personal site',
    add: 'Add',
    placeholder: {
      github: 'github.com/ananya',
      linkedin: 'linkedin.com/in/ananya-rao',
      portfolio: 'ananya.dev',
    },
    invalid: "That link won't work here. Paste the full address, like github.com/ananya.",
  },
  edit: 'Edit profile',
  editProfile: 'Edit profile',
  finishEditing: 'Done editing',
  empty: 'Not added yet',
  remove: (item: string) => `Remove ${item}`,
  suggestions: (label: string) => `${label}, suggestions`,
  fieldEdit: (label: string, value: string) => `${label}: ${value}. Edit`,
  saving: 'Saving',
  saved: 'Saved',
  failed: "That didn't save. Try again.",
  done: 'Looks like me',
}

/** The one problem everyone gets. The owner's statement, set to land on a phone. */
export const challenge = {
  kicker: 'The challenge',
  title: 'Small shops run on WhatsApp and a notebook.',
  body: [
    'Orders get missed. Credit goes unwritten.',
    "At the end of the day, the owner can't say what sold or who owes them.",
  ],
  asks: [
    "Pick who you're building for.",
    'Find out where it really breaks.',
    'Build what fixes it.',
  ],
  depth:
    'One owner and one fix is a real start. Credit, stock, staff, payments, AI: how far you take it is yours.',
  next: 'What happens next',
  timeline: [
    { when: 'Fri 9 and Sat 10 Oct', what: 'Research. Building opens when you send it.' },
    { when: 'Fri 16 Oct, 6 pm', what: 'Stop 1. A first version on a live link.' },
    { when: 'Fri 23 Oct, 6 pm', what: 'Stop 2. Live, with sign-in and real data.' },
    { when: 'Mon 26 Oct, 6 pm', what: 'Stop 3. Real owners using it, and a demo.' },
  ],
  start: 'Start your research',
  starting: 'Opening your research',
  failed: "That didn't go through. Try again in a moment.",
}

/** Days 1 and 2. Nobody approves research; sending it opens the plan. */
export const research = {
  title: 'Find out where it really breaks.',
  lead: "Fri 9 and Sat 10 Oct. Read what's out there, talk to owners if you can, then say it in your words.",
  saved: 'Saved',
  secondary: {
    kicker: 'Secondary research',
    title: 'Look at 3 apps owners use',
    lead: 'Secondary research means reading what others already found: apps, their reviews, articles.',
    name: 'App or tool',
    namePlaceholder: 'An app owners use, like Khatabook',
    note: 'What it gets wrong for owners',
    notePlaceholder: 'What its reviews, or the owners you know, say about it',
    app: (n: number) => `App ${n}`,
    reading: 'Anything you read online',
    readingHint: 'Optional. A link to an article, a report or a video.',
    readingPlaceholder: 'Link to an article',
    addReading: 'Add a link',
  },
  primary: {
    kicker: 'Primary research',
    title: 'If you can, talk to 2 owners',
    lead: 'Primary research means going to people yourself: talking to them, or watching them work.',
    who: 'Who',
    whoPlaceholder: 'Ramesh, runs a kirana in Jayanagar',
    breaks: 'Where it breaks for them',
    breaksPlaceholder: 'Credit customers forget what they owe, and so does he',
    said: 'One thing they said',
    saidPlaceholder: 'I lose 2 or 3 orders every Sunday.',
    owner: (n: number) => `Owner ${n}`,
    add: 'Add an owner',
    remove: 'Remove',
  },
  yours: {
    kicker: 'In your words',
    title: 'Say it your way',
    forWho: 'Who are you building for?',
    forWhoPlaceholder: 'Home bakers who take cake orders on WhatsApp',
    forWhoHint: 'One kind of business. The narrower, the better.',
    problem: 'The problem, in 3 lines',
    problemPlaceholder:
      'Orders arrive on WhatsApp, Instagram and calls. Meera writes them on paper. Last month she missed 2 birthday cakes.',
    moment: 'The moment it breaks',
    momentPlaceholder: "Saturday night, when tomorrow's orders are spread across 3 apps",
  },
  needs: 'To send: who it is for, the problem, the moment, and 3 apps.',
  save: 'Save for later',
  saving: 'Saving',
  send: 'Send my research',
  sending: 'Sending',
  update: 'Save changes',
  sentNote: "Sent. Change it whenever you learn more; it's yours.",
  failed: "That didn't save. Everything you wrote is still here. Try again.",
  badLink: "One of your links won't work. Paste the full address.",
  sent: {
    title: "You're building.",
    lead: "Nobody approves research. It's yours, and your plan is open. Your first step is waiting.",
    go: "See today's steps",
  },
}

/** Today, the plan, and every step in it. Words for each step are in content/plan.ts. */
export const plan = {
  nav: {
    label: 'Your build',
    today: 'Today',
    plan: 'Plan',
    stops: 'Stops',
    messages: 'Messages',
    profile: 'Profile',
    pod: 'Pod',
  },
  day: (n: string, of: string) => `Day ${n} of ${of}`,
  before: 'Starts Fri 9 Oct',
  over: 'The sprint is over. Keep it running for your owners.',
  nextStop: (n: string) => `Stop ${n} closes`,
  inTime: (left: string) => `in ${left}`,
  units: { day: 'd', hour: 'h', minute: 'min' },
  allStopsDone: 'All 3 stops are behind you.',
  workshopToday: (name: string) => `Workshop today: ${name}`,
  workshopOn: (name: string) => `Workshop: ${name}`,
  commit: 'Every day: commit your work to GitHub.',
  checkins: 'This week, Pragati and Chandu meet each of you, one to one.',
  stillOpen: 'Still open',
  fixes: 'Fixes from the team',
  today: 'Today',
  upNext: 'Up next',
  nothingToday: 'Nothing new today. Catch up, or work ahead in your plan.',
  allDone: 'All done for today. Work ahead if you like.',
  workAhead: 'See the whole plan',
  due: (day: string) => `Due ${day}`,
  doneMeans: 'Done means',
  example: 'For example',
  openCard: (n: string) => `Open card ${n}`,
  tool: (name: string) => `Tool: ${name}`,
  tick: (title: string) => `Mark done: ${title}`,
  untick: (title: string) => `Mark not done: ${title}`,
  more: (title: string) => `Show more: ${title}`,
  save: 'Save',
  saved: 'Saved',
  saving: 'Saving',
  needed: 'Add this first, then tick it.',
  badLink: {
    github: "Paste your repo's link, like github.com/you/your-app.",
    live: 'Paste the full address of your live app.',
    design: 'Paste a Figma or Google Drive link.',
    video: 'Paste a YouTube, Loom or Google Drive link.',
    doc: 'Paste the full address, starting with https.',
    screenshot: 'Paste a Google Drive link to the screenshot.',
  },
  badNumber: 'A whole number, like 7.',
  failed: "That didn't save. Try again in a moment.",
  openStop: (n: string) => `Open stop ${n}`,
  stretch: {
    pick: 'Pick 2',
    own: 'Or propose your own',
    ownPlaceholder: 'Owners can reorder with one tap',
    chosen: (n: string) => `${n} of 2 chosen`,
  },
  title: 'Your plan',
  lead: 'Every step until 30 Oct. Work ahead whenever you like.',
  progress: (done: string, of: string) => `${done} of ${of} done`,
  phases: {
    research: 'Research',
    week1: 'Week 1 · Build it',
    week2: 'Week 2 · Make it real',
    week3: 'Week 3 · Real owners',
    after: 'After stop 3',
  },
  researchStep: 'Your research',
  researchSent: 'Sent',
  researchEdit: 'Open your research',
  tools: {
    title: 'Your tools',
    names: {
      claude: 'Claude Pro',
      figma: 'Figma',
      cursor: 'Cursor',
      copilot: 'GitHub Copilot',
      github: 'GitHub',
      supabase: 'Supabase',
      gcloud: 'Google Cloud',
      vercel: 'Vercel',
      owners: 'Owners',
    },
    lines: {
      claude: 'Thinking, planning, and understanding code.',
      figma: 'Design, if you like designing first.',
      cursor: 'Where you write code, with AI beside you.',
      copilot: 'Writes code with you, inside Cursor.',
      github: 'Where your code lives. Commit every day.',
      supabase: 'Sign-in, your database and storage.',
      gcloud: 'The Google sign-in client, and a free Gemini key.',
      vercel: 'Puts your app on a live link.',
      owners: 'Real owners, in person or on a call.',
    },
  },
  workshops: {
    figma: 'Figma',
    cursor: 'Cursor and GitHub Copilot',
    cloud: 'Google Cloud Console and Supabase',
    vercel: 'Vercel',
  },
  workshopsTitle: 'Workshops',
  workshopDone: 'Done',
  helpRule: 'Stuck for 20 minutes with Claude or Cursor? Message the team.',
}

/** The 3 hard stops. Field labels per track are in content/plan.ts. */
export const stops = {
  title: 'Stops',
  lead: 'At each stop, the team sees your work and replies with a rating and notes.',
  names: { '1': 'Prototype', '2': 'Live product', '3': 'Real users' },
  heading: (n: string, name: string) => `Stop ${n} · ${name}`,
  closes: (when: string) => `Closes ${when}`,
  closed: (when: string) => `Closed ${when}`,
  state: {
    none: 'Not started',
    draft: 'Draft saved',
    sent: 'Sent',
    late: 'Sent late',
    locked: 'Locked',
  },
  sentNote: (when: string) => `Sent ${when}. You can change it until 6 pm.`,
  lateNote: (when: string) => `Sent late, on ${when}.`,
  lockedNote: 'Locked at 6 pm. This is what the team sees.',
  closedNote: 'This closed at 6 pm. You can still send it once, and it will show as late.',
  researchTitle: 'Your research',
  researchNote: 'Sent. The team reads it with this stop.',
  optional: 'Optional',
  yes: 'Yes',
  save: 'Save draft',
  saving: 'Saving',
  send: (n: string) => `Send stop ${n}`,
  sendChanges: 'Send changes',
  sending: 'Sending',
  saved: 'Draft saved',
  sentNow: 'Sent. The team will review it.',
  required: "This one's needed to send.",
  failed: "That didn't save. Everything you wrote is still here. Try again.",
  locked: 'This stop is locked. The team has what you sent.',
  open: 'Open',
  review: {
    title: 'From the team',
    ratings: { green: 'On track', amber: 'A few fixes', red: "Let's meet tomorrow" },
    lines: {
      green: 'Keep going.',
      amber: "Work through the fixes. We'll check in within 2 days.",
      red: "We'll meet tomorrow, one to one, and agree a smaller scope.",
    },
    fixes: 'Your fix list',
    waiting: 'The team will review it after 6 pm.',
  },
  stretchOwn: (text: string) => `Your own: ${text}`,
}

/** Stuck? Message the team. One thread per founder. */
export const messages = {
  open: 'Stuck? Message the team',
  title: 'Messages',
  lead: 'Stuck for 20 minutes with Claude or Cursor? Tell the team in 3 lines. We reply here and by email.',
  empty: 'No messages yet. When you get stuck, this is where to say so.',
  label: 'Where are you stuck?',
  placeholder: 'Card 3: Vercel says the build failed. I checked the keys twice. Screenshot below.',
  hint: "What you were trying, and what you've tried. 3 lines at most.",
  count: (n: string, max: string) => `${n} of ${max}`,
  tooManyLines: 'Keep it to 3 lines.',
  screenshot: 'Screenshot link',
  screenshotHint:
    'Optional. Upload it to Google Drive, set it to anyone with the link, and paste the link.',
  screenshotPlaceholder: 'drive.google.com/file/d/...',
  badScreenshot: 'Paste a Google Drive link to the screenshot.',
  about: (title: string) => `About: ${title}`,
  send: 'Message the team',
  sending: 'Sending',
  sent: "Sent. We'll reply here, and by email.",
  failed: "That didn't send. Your message is still here. Try again.",
  you: 'You',
  team: 'The ForgeX team',
  close: 'Close',
  viewScreenshot: 'Screenshot',
  back: 'Back to your research',
  removeStep: 'Not about a step',
}

export const page = {
  continue: (level: string) => `Continue: ${level}`,
  you: 'You',
  team: 'The ForgeX team',
  console: 'Console',
  sections: {
    profile: 'Your profile',
    theirProfile: 'Profile',
    build: 'Your build',
    theirBuild: 'Their build',
  },
  building: {
    forWho: 'Building for',
    problem: 'The problem',
    moment: 'The moment it breaks',
    notYet: 'Their research is on its way.',
    yoursNotYet: 'Your build appears here once you send your research.',
  },
  links: {
    title: 'Links',
    live: 'Live app',
    repo: 'Code',
    design: 'Design',
    video: 'Demo video',
    none: 'No links yet.',
  },
  progress: (done: string, of: string) => `${done} of ${of} steps done`,
  stopSent: 'Sent',
  stopLate: 'Sent late',
  stopNot: 'Not yet',
  teamOnly: 'Team only',
  teamFields: {
    email: 'Email',
    track: 'Track',
    pod: 'Pod',
    h1: 'Hackathon 1',
    level: 'Onboarding',
    active: 'Last active',
    steps: 'Steps',
  },
  podOf: (n: string) => `Pod ${n}`,
  mentorOf: (n: string) => `Mentor, pod ${n}`,
  research: {
    title: 'Their research',
    apps: 'Apps they looked at',
    talks: 'Owners they talked to',
    reading: 'What they read',
    none: 'None',
  },
  checkins: {
    title: 'Check-in notes',
    lead: 'From the 1:1s, 27 to 30 Oct. Founders never see these.',
    label: 'New check-in note',
    placeholder: 'What they showed, where they are stuck, what we agreed.',
    add: 'Save note',
    none: 'No check-in notes yet.',
    failed: "That didn't save. Try again.",
  },
  messages: 'Messages',
  openThread: 'Open their messages',
}

/** The team's account menu. Founders have none. */
export const account = {
  open: (who: string) => `Account: ${who}`,
  signOut: 'Sign out',
}

export const consoleCopy = {
  nav: {
    label: 'Console',
    founders: 'Founders',
    messages: 'Messages',
    stops: 'Stops',
    pods: 'Pods',
    bank: 'Bank',
  },
  founders: {
    title: 'Founders',
    search: 'Search founders',
    searchPlaceholder: 'Ananya',
    export: 'Export CSV',
    columns: {
      name: 'Founder',
      track: 'Track',
      pod: 'Pod',
      forWho: 'Building for',
      steps: 'Steps',
      behind: 'Behind',
      stop: 'Stops',
      active: 'Last active',
    },
    /** Where each founder is in onboarding, then building. */
    steps: ['Not started', 'Arrived', 'Archetype', 'Profile', 'Researching', 'Building'],
    all: 'All',
    allTracks: 'All tracks',
    allPods: 'All pods',
    noPod: 'No pod',
    behindOnly: 'Behind',
    waitingOnly: 'Waiting on us',
    none: 'No founders match.',
    dash: '—',
    stepsOf: (done: string, due: string) => `${done} / ${due}`,
    behindBy: (n: string) => `${n} behind`,
    filters: 'Filters',
  },
  stops: {
    title: (n: string, name: string) => `Stop ${n} · ${name}`,
    closes: (when: string) => `Closes ${when}`,
    pick: 'Stop',
    filters: {
      all: 'All',
      notSent: 'Not sent',
      unrated: 'To review',
      green: 'Green',
      amber: 'Amber',
      red: 'Red',
    },
    late: 'Late',
    draft: 'Draft only',
    sentAt: (when: string) => `Sent ${when}`,
    rating: 'Rating',
    ratings: { green: 'Green', amber: 'Amber', red: 'Red' },
    notes: 'Notes to the founder',
    notesPlaceholder: 'What works, what to change. They read every word.',
    fixes: 'Fix list',
    fixesHint: 'One fix per line. Each becomes a tick on their Today.',
    fixesPlaceholder: 'Sign-in fails on the live link',
    save: 'Save review',
    saving: 'Saving',
    saved: 'Saved',
    failed: "That didn't save. Try again.",
    reviewedBy: (who: string, when: string) => `${who} · ${when}`,
    none: 'No founders match.',
    empty: 'Nothing sent',
    research: 'Research',
    counts: (sent: string, of: string) => `${sent} of ${of} sent`,
    open: 'Review',
    close: 'Close',
  },
  messages: {
    title: 'Messages',
    views: { label: 'Messages view', waiting: 'Waiting on us', answered: 'Answered' },
    empty: {
      waiting: 'Nobody is waiting. Every message has a reply.',
      answered: 'No answered threads yet.',
    },
    reply: 'Reply',
    replyPlaceholder: 'Answer in a few lines. Link a doc or a card if it helps.',
    send: 'Send reply',
    sending: 'Sending',
    failed: "That didn't send. Try again.",
    about: (title: string) => `About: ${title}`,
    screenshot: 'Screenshot',
    waitingFor: (time: string) => `Waiting ${time}`,
    open: 'Open their profile',
  },
  pods: {
    title: 'Pods',
    lead: '5 pods with daily standups. Each pod has a peer mentor from the volunteers.',
    pod: (n: string) => `Pod ${n}`,
    members: (n: string) => `${n} founders`,
    mentors: 'Mentors',
    noMentor: 'No mentor yet',
    unassigned: 'Not in a pod',
    move: (name: string) => `Pod for ${name}`,
    addMentor: (n: string) => `Add a mentor to pod ${n}`,
    pickMentor: 'Pick a mentor',
    remove: (name: string) => `Remove ${name}`,
    none: 'None',
    failed: "That didn't save. Try again.",
  },
  bank: {
    title: 'Bank',
    filters: { draft: 'Drafts', approved: 'Live', rejected: 'Archived', all: 'All' },
    levels: { all: 'Any difficulty' },
    approve: 'Approve',
    reject: 'Archive',
    draft: 'Take down',
    restore: 'Restore to drafts',
    means: {
      draft: "Founders don't see drafts.",
      approved: 'Live. Founders can be matched to this.',
      rejected: 'Archived. Founders never see it.',
    },
    edit: 'Edit',
    save: 'Save',
    cancel: 'Cancel',
    approveAll: (n: number) => `Approve all ${n} drafts`,
    evidence: 'Evidence',
    scores: 'Scores',
    whyNow: 'Why now',
    players: "Who's there already",
    empty: 'No problems with this status.',
    status: { draft: 'Draft', approved: 'Live', rejected: 'Archived' },
    fields: {
      title: 'Title',
      problem: 'Problem',
      challenge: 'Challenge',
      difficulty: 'Difficulty',
    },
    strength: (n: number) => `Signal strength ${n} of 5`,
    editedBy: (who: string, date: string) => `${who} · ${date}`,
  },
  wall: 'The wall',
  setup: {
    title: 'Setup check',
    allGood: 'Everything is wired up.',
    failing: (n: number) => (n === 1 ? '1 thing needs fixing.' : `${n} things need fixing.`),
    pass: 'Working',
    fail: 'Needs fixing',
    signIn: 'Google sign-in',
    signInOk: 'Working. You signed in to see this page.',
    set: 'Set',
    missing: 'Not set',
    mock: 'Mock mode',
    mockOn: 'On. Nothing is read from or written to the Sheet. Remove MOCK_BACKEND.',
    mockOff: 'Off. The Sheet is the store.',
    sheet: 'Google Sheet',
    sheetMissing: 'SHEET_ID, GOOGLE_SA_EMAIL or GOOGLE_SA_KEY is not set.',
    sheetOk: 'Reached with the service account.',
    sheetSkipped: 'Not checked while mock mode is on.',
    rows: (n: number) => `${n} rows`,
    plan: 'The plan',
    planLine: (stop: string, when: string) => `Next: stop ${stop}, ${when}.`,
    planOver: 'All 3 stops have closed.',
    bank: 'Problem bank',
    bankOn: 'On. The team can read it in the console. Founders never see it.',
    bankOff: 'Off. Its data stays in the Sheet. Set PROBLEM_BANK=on to read it here.',
    email: 'Reply emails',
    emailOn: 'On, through Resend.',
    emailOff: 'Off. Replies show in the portal only. That is fine.',
  },
  mentor: {
    title: (n: string) => `Pod ${n}`,
    lead: "The founders you mentor: today's steps, and anything overdue.",
    none: "You're not mentoring a pod.",
    today: 'Today',
    behind: 'Behind',
    active: 'Last active',
  },
}

/** Reply emails. */
export const email = {
  subject: 'The team replied to your message',
  hi: (first: string) => `Hi ${first},`,
  lead: 'The team replied:',
  readMore: 'Read it, and reply, in ForgeX:',
  signOff: 'The ForgeX team',
}
