import 'server-only'
import type { PlanStep, StopField } from '@/lib/steps'

/**
 * The plan, step by step: what each founder does on each day of the sprint,
 * in their words. Written to docs/VOICE.md and held to the same copy lint as
 * content/copy.ts. Server only, because each step names the tracks it's for,
 * and track names never reach a founder's browser.
 *
 * Step IDs are frozen once founders can tick them. Change the words freely;
 * never reuse an ID for a different step.
 *
 * The running example is one founder's research: Meera, a home baker who
 * takes cake orders on WhatsApp and Instagram.
 */

const G = ['guided'] as const
const S = ['structured'] as const
const A = ['autonomous'] as const
const SA = ['structured', 'autonomous'] as const
const ALL = ['guided', 'structured', 'autonomous'] as const

export const PLAN_STEPS: PlanStep[] = [
  // Week 1 · Sun 11 Oct · decide what to build
  {
    id: 'g-flow',
    day: '2026-10-11',
    tracks: G,
    tool: 'claude',
    title: "Choose the one flow you'll build",
    what: 'Paste your research into Claude and ask which single flow fixes the moment it breaks. Pick one.',
    done: 'You can say it in one line: the owner does this, and that stops happening.',
    example: 'Meera types an order once and sees every cake due tomorrow.',
  },
  {
    id: 's-flows',
    day: '2026-10-11',
    tracks: S,
    tool: 'claude',
    title: 'Choose 2 or 3 flows that connect',
    what: 'Ask Claude to turn your research into flows. Keep the 2 or 3 that touch the moment it breaks.',
    done: 'Each flow fits in one line, and you can say how they connect.',
    example: 'Orders, a credit book, and a weekly view of who owes what.',
  },
  {
    id: 'a-product',
    day: '2026-10-11',
    tracks: A,
    tool: 'claude',
    title: 'Shape the product, with AI at the centre',
    what: "Decide what the AI does that a form can't. Then plan the screens around it.",
    done: 'One paragraph on what it does, for whom, and where AI sits.',
    example:
      'Owners forward WhatsApp orders. AI turns them into order lines. The owner sees dues and what to reorder.',
  },
  {
    id: 'sketch',
    day: '2026-10-11',
    tracks: ALL,
    tool: 'figma',
    title: 'Sketch every screen',
    what: 'Paper is fine. Use Figma if you like designing first. Draw one box per screen, with arrows between them.',
    done: 'A photo or Figma link with every screen in your flow.',
    input: { kind: 'link', link: 'design', label: 'Link to your sketch or Figma', optional: true },
  },

  // Mon 12 Oct · your repo
  {
    id: 'g-card-1',
    day: '2026-10-12',
    tracks: G,
    tool: 'github',
    card: 1,
    title: 'Make your own copy of the starter',
    what: 'Make a GitHub account, then make your own copy of the Mesa starter. Card 1 shows every click.',
    done: 'You have a repo at github.com/your-name/your-repo.',
    input: { kind: 'link', link: 'github', label: 'Your repo link' },
  },
  {
    id: 's-repo',
    day: '2026-10-12',
    tracks: S,
    tool: 'github',
    title: 'Create your repo',
    what: "Start from the Mesa starter, or a fresh Next.js app if you'd rather. It lives in your own GitHub.",
    done: 'Your repo exists, with a first commit.',
    input: { kind: 'link', link: 'github', label: 'Your repo link' },
  },
  {
    id: 's-system',
    day: '2026-10-12',
    tracks: S,
    tool: 'figma',
    title: 'Make a small design system',
    what: 'Pick 2 colours, 1 font, and how a button, a field and a card look. Use them everywhere.',
    done: 'One page in Figma, or one file in your code, that every screen follows.',
  },
  {
    id: 'a-repo',
    day: '2026-10-12',
    tracks: A,
    tool: 'supabase',
    title: 'Repo, database and tables',
    what: 'Create the repo and a Supabase project. Write the tables your product needs, with row-level security from day 1.',
    done: 'The tables exist, and a test row saves and reads back.',
    input: { kind: 'link', link: 'github', label: 'Your repo link' },
  },
  {
    id: 'a-arch',
    day: '2026-10-12',
    tracks: A,
    tool: 'claude',
    title: 'Write your architecture note',
    what: "One page: screens, tables, where AI sits, and what you'll fake for now. Put it in your repo as ARCHITECTURE.md.",
    done: 'The note is in your repo, and a stranger could follow it.',
    input: { kind: 'link', link: 'doc', label: 'Link to the note' },
  },

  // Tue 13 Oct · Cursor and Copilot workshop
  {
    id: 'g-card-2',
    day: '2026-10-13',
    tracks: G,
    tool: 'cursor',
    card: 2,
    title: 'Run it on your laptop with Cursor',
    what: "Open your repo in Cursor and run it. Today's workshop walks you through it.",
    done: 'localhost:3000 shows the starter on your laptop.',
  },
  {
    id: 's-screens',
    day: '2026-10-13',
    tracks: S,
    tool: 'cursor',
    title: 'Code every screen with sample data',
    what: 'Build each screen in your flows with made-up data kept in one file. No database yet.',
    done: 'You can click through every screen on your laptop.',
  },
  {
    id: 'a-core',
    day: '2026-10-13',
    tracks: A,
    tool: 'cursor',
    title: 'Get the core flow working',
    what: 'One full path through the product, saving to Supabase. Rough is fine.',
    done: "You can do the main thing end to end, and it's saved.",
  },

  // Wed 14 Oct · go live
  {
    id: 'g-card-3',
    day: '2026-10-14',
    tracks: G,
    tool: 'vercel',
    card: 3,
    title: 'Go live on Vercel',
    what: "Use the Deploy button in the starter's README. The setup screen is fine for now.",
    done: 'Your own link opens on your phone.',
    input: { kind: 'link', link: 'live', label: 'Your live link' },
  },
  {
    id: 's-live',
    day: '2026-10-14',
    tracks: S,
    tool: 'vercel',
    title: 'Go live on Vercel',
    what: 'Import your repo into Vercel. From now on, every push to GitHub updates your link.',
    done: 'Your link opens on your phone.',
    input: { kind: 'link', link: 'live', label: 'Your live link' },
  },
  {
    id: 'a-ai',
    day: '2026-10-14',
    tracks: A,
    tool: 'claude',
    title: 'AI reads a real order',
    what: "Use the Claude API, or a free Gemini key if you don't have one. Give it a real message from your research.",
    done: 'A pasted message becomes order lines in your database.',
  },

  // Thu 15 Oct
  {
    id: 'g-card-4',
    day: '2026-10-15',
    tracks: G,
    tool: 'cursor',
    card: 4,
    title: "Your shop's name and colours",
    what: 'Change the name and colours to fit the business you chose. The card has the prompt to paste.',
    done: 'Your live link shows your name and colours.',
  },
  {
    id: 's-examples',
    day: '2026-10-15',
    tracks: S,
    tool: 'owners',
    title: 'Put 10 real examples through it',
    what: "Collect 10 real orders or entries from owners or your research. Enter each one and note what doesn't fit.",
    done: "You know which of the 10 work, and why the rest don't.",
    input: { kind: 'number', label: 'How many of the 10 work?' },
  },
  {
    id: 'a-live',
    day: '2026-10-15',
    tracks: A,
    tool: 'vercel',
    title: 'Go live on Vercel',
    what: 'Import your repo into Vercel and add your keys as environment variables.',
    done: 'The core flow works on your live link.',
    input: { kind: 'link', link: 'live', label: 'Your live link' },
  },
  {
    id: 'a-stretch',
    day: '2026-10-15',
    tracks: A,
    title: 'Choose 2 stretch features',
    what: 'Pick 2 from the list, or propose your own. Choose what your research says owners need.',
    done: 'You can say why each one matters to an owner.',
    input: { kind: 'stretch' },
  },

  // Fri 16 Oct · stop 1
  {
    id: 'g-card-5',
    day: '2026-10-16',
    tracks: G,
    tool: 'cursor',
    card: 5,
    title: 'Build the first screen of your flow',
    what: 'Build the screen your research pointed to, with sample data. Check it on your phone.',
    done: 'The screen is on your live link.',
  },
  {
    id: 'stop-1',
    day: '2026-10-16',
    tracks: ALL,
    title: 'Send stop 1 by 6 pm',
    what: 'Your repo, your live link and your research go to the team. You can edit it until 6 pm.',
    done: 'Sent before 6 pm IST.',
    input: { kind: 'stop', stop: 1 },
  },

  // Week 2 · Sat 17 Oct
  {
    id: 'g-card-6',
    day: '2026-10-17',
    tracks: G,
    tool: 'cursor',
    card: 6,
    title: 'Make the products fit your business',
    what: 'Swap the sample products for what your owners really sell, at real prices.',
    done: "The product list looks like a real shop's.",
  },
  {
    id: 's-flow-2',
    day: '2026-10-17',
    tracks: S,
    tool: 'cursor',
    title: 'Build your second flow',
    what: 'Build the next flow you chose, on sample data. Link it to the first.',
    done: 'You can move from one flow to the other without a dead end.',
  },
  {
    id: 'a-many',
    day: '2026-10-17',
    tracks: A,
    tool: 'supabase',
    title: 'Many shops, each sees only its own',
    what: "Make shops a table and lock every query to the signed-in owner's shop with row-level security.",
    done: "Sign in as 2 owners. Neither can see the other's data.",
  },

  // Sun 18 Oct
  {
    id: 'g-card-7',
    day: '2026-10-18',
    tracks: G,
    tool: 'cursor',
    card: 7,
    title: 'Take an order from a pasted message',
    what: 'Paste a real WhatsApp order, pick the products and quantities, and save it.',
    done: 'A pasted message becomes an order in the list.',
  },
  {
    id: 's-db',
    day: '2026-10-18',
    tracks: S,
    tool: 'supabase',
    title: 'Save to a real database',
    what: "Follow the Supabase steps in the starter's README. Wednesday's workshop covers it if you get stuck.",
    done: 'What you enter is still there after a refresh.',
  },
  {
    id: 'a-pay',
    day: '2026-10-18',
    tracks: A,
    title: 'Payments in test mode',
    what: 'Add Razorpay or UPI in test mode, for a subscription or an order.',
    done: 'A test payment goes through and shows in your app.',
  },

  // Mon 19 Oct
  {
    id: 'g-card-8',
    day: '2026-10-19',
    tracks: G,
    tool: 'cursor',
    card: 8,
    title: 'Order status: new, ready, delivered, paid',
    what: 'Add one tap to move an order along. Let the owner filter the list by status.',
    done: 'An order moves from new to paid in 3 taps.',
  },
  {
    id: 's-search',
    day: '2026-10-19',
    tracks: S,
    tool: 'copilot',
    title: 'Search, filter and edit',
    what: 'Let the owner find any entry in 2 taps, and fix a mistake.',
    done: "You can find last week's order by name and edit it.",
  },
  {
    id: 'a-stretch-1',
    day: '2026-10-19',
    tracks: A,
    tool: 'cursor',
    title: 'Build stretch feature 1',
    what: 'Build the first stretch feature you chose. Ship a small version today.',
    done: 'It works on your live link, end to end.',
  },
  {
    id: 'g-owner',
    day: '2026-10-19',
    tracks: G,
    tool: 'owners',
    title: "Find the owner who'll use it",
    what: "Ask an owner you spoke to if they'll try it from Saturday. Get a yes and a time.",
    done: '1 owner has said yes.',
  },
  {
    id: 's-owners',
    day: '2026-10-19',
    tracks: S,
    tool: 'owners',
    title: 'Get 3 owners to say yes',
    what: 'Ask 3 owners to use it for a week. Show the first one what you have, even on sample data.',
    done: '3 owners have said yes, and 1 has seen it.',
  },
  {
    id: 'a-owners',
    day: '2026-10-19',
    tracks: A,
    tool: 'owners',
    title: 'Line up 5 or more owners',
    what: 'Ask 5 owners to use it from Saturday. Start the first one now.',
    done: '5 owners have said yes, and 1 is already using it.',
  },

  // Tue 20 Oct
  {
    id: 'g-card-9',
    day: '2026-10-20',
    tracks: G,
    tool: 'cursor',
    card: 9,
    title: "Today's orders and total",
    what: "Show today's orders and today's total on the home screen.",
    done: "The home screen shows today's count and total, in rupees.",
  },
  {
    id: 's-view',
    day: '2026-10-20',
    tracks: S,
    tool: 'cursor',
    title: "The owner's daily view",
    what: 'One screen the owner opens every morning: what sold, and who owes money.',
    done: 'The view uses your real data and fits on a phone.',
  },
  {
    id: 'a-messages',
    day: '2026-10-20',
    tracks: A,
    tool: 'owners',
    title: 'Collect 50 real messages',
    what: 'Gather 50 real order messages from your owners, with what each one really meant.',
    done: '50 messages, each with the right answer written next to it.',
  },

  // Wed 21 Oct · Google Cloud and Supabase workshop
  {
    id: 'g-card-10',
    day: '2026-10-21',
    tracks: G,
    tool: 'supabase',
    card: 10,
    title: 'Connect Supabase and Google sign-in',
    what: "Follow card 10 in today's workshop. You'll paste 2 keys and run 1 file.",
    done: 'You sign in with Google on your live link, and your data saves.',
  },
  {
    id: 's-signin',
    day: '2026-10-21',
    tracks: S,
    tool: 'gcloud',
    title: 'Google sign-in and staff access',
    what: 'Add Google sign-in, then a staff role that can take orders but not see the money.',
    done: 'An owner and a staff member see different things.',
  },
  {
    id: 'a-monitor',
    day: '2026-10-21',
    tracks: A,
    title: 'Error monitoring',
    what: "Add error monitoring, such as Sentry's free plan. You hear about a crash before the owner does.",
    done: 'A test error shows up in your monitoring.',
  },

  // Thu 22 Oct
  {
    id: 'g-card-11',
    day: '2026-10-22',
    tracks: G,
    tool: 'owners',
    card: 11,
    title: 'Put in real data from one owner',
    what: "Sit with your owner and enter a real day's orders together.",
    done: 'Real orders are in your app, not sample ones.',
  },
  {
    id: 's-upi',
    day: '2026-10-22',
    tracks: S,
    tool: 'cursor',
    title: 'Add a UPI payment link',
    what: 'Let the owner send a UPI link for what a customer owes.',
    done: 'The link opens a UPI app with the right amount.',
  },
  {
    id: 's-tests',
    day: '2026-10-22',
    tracks: S,
    tool: 'copilot',
    title: 'Write tests for totals and dues',
    what: 'Ask Copilot to write tests for the sums an owner trusts you with.',
    done: 'The tests pass, and fail when a sum is wrong.',
  },
  {
    id: 'a-accuracy',
    day: '2026-10-22',
    tracks: A,
    tool: 'claude',
    title: 'Measure AI accuracy on 50 messages',
    what: 'Run all 50 messages through your AI and count how many come out right.',
    done: 'You have one number, and a list of what it got wrong.',
    input: { kind: 'number', label: 'How many of the 50 came out right?' },
  },

  // Fri 23 Oct · Vercel workshop · stop 2
  {
    id: 'g-card-12',
    day: '2026-10-23',
    tracks: G,
    card: 12,
    title: 'Check every screen on your phone',
    what: 'Open each screen on your phone and fix anything you have to pinch or zoom.',
    done: 'Every screen works one-handed on a phone.',
  },
  {
    id: 'phone',
    day: '2026-10-23',
    tracks: SA,
    title: 'Check every screen on your phone',
    what: 'Open each screen on your phone and fix anything you have to pinch or zoom.',
    done: 'Every screen works one-handed on a phone.',
  },
  {
    id: 'stop-2',
    day: '2026-10-23',
    tracks: ALL,
    title: 'Send stop 2 by 6 pm',
    what: 'Your live link, with Google sign-in and real data. You can edit it until 6 pm.',
    done: 'Sent before 6 pm IST.',
    input: { kind: 'stop', stop: 2 },
  },

  // Week 3 · Sat 24 Oct · real users
  {
    id: 'g-card-13',
    day: '2026-10-24',
    tracks: G,
    tool: 'owners',
    card: 13,
    title: "Put it in your owner's hands",
    what: 'Set it up on their phone and watch them take real orders.',
    done: 'Your owner has used it for real orders.',
  },
  {
    id: 's-users',
    day: '2026-10-24',
    tracks: S,
    tool: 'owners',
    title: '3 owners using it',
    what: "Set it up on each owner's phone. Check in with each one every day.",
    done: '3 owners use it for real this week.',
  },
  {
    id: 'a-users',
    day: '2026-10-24',
    tracks: A,
    tool: 'owners',
    title: '5 or more owners using it',
    what: 'Set it up with each owner and log what they do each day.',
    done: '5 owners use it, and you can see their numbers.',
  },
  {
    id: 'a-stretch-2',
    day: '2026-10-24',
    tracks: A,
    tool: 'cursor',
    title: 'Build stretch feature 2',
    what: 'Build the second stretch feature, sized to ship in 2 days.',
    done: 'It works on your live link, end to end.',
  },

  // Sun 25 Oct
  {
    id: 'g-card-14',
    day: '2026-10-25',
    tracks: G,
    tool: 'github',
    card: 14,
    title: 'Write the README case study',
    what: "Who it's for, what you found, what you built, and the numbers. Add screenshots from a phone.",
    done: 'Someone outside Mesa could read it and understand your work.',
  },
  {
    id: 'readme',
    day: '2026-10-25',
    tracks: SA,
    tool: 'github',
    title: 'Write the README case study',
    what: "Who it's for, what you found, what you built, and the numbers. Add screenshots from a phone.",
    done: 'Someone outside Mesa could read it and understand your work.',
  },
  {
    id: 'numbers',
    day: '2026-10-25',
    tracks: ALL,
    tool: 'owners',
    title: 'Count the usage',
    what: 'Count what owners did with it: orders taken, days used, money tracked.',
    done: 'You have numbers you can say out loud in the demo.',
    input: {
      kind: 'text',
      label: 'Your numbers',
      placeholder: '64 orders in 3 days, from 1 owner',
    },
  },

  // Mon 26 Oct · stop 3
  {
    id: 'g-card-15',
    day: '2026-10-26',
    tracks: G,
    card: 15,
    title: 'Record the 3-minute demo',
    what: "Film it on a phone, using the real app. Show your owner's real orders.",
    done: 'A 3-minute video link that anyone can open.',
    input: { kind: 'link', link: 'video', label: 'Your video link' },
  },
  {
    id: 'demo',
    day: '2026-10-26',
    tracks: SA,
    title: 'Record the 3-minute demo',
    what: "Film it on a phone, using the real app. Show real owners' use.",
    done: 'A 3-minute video link that anyone can open.',
    input: { kind: 'link', link: 'video', label: 'Your video link' },
  },
  {
    id: 'stop-3',
    day: '2026-10-26',
    tracks: ALL,
    title: 'Send stop 3 by 6 pm',
    what: 'Your demo, your README and your numbers go to the team. You can edit it until 6 pm.',
    done: 'Sent before 6 pm IST.',
    input: { kind: 'stop', stop: 3 },
  },

  // Tue 27 to Fri 30 Oct · keep building, and check-ins
  {
    id: 'checkin',
    day: '2026-10-27',
    tracks: ALL,
    title: 'Your check-in with the team',
    what: 'Pragati and Chandu meet each of you this week. Bring your phone, with the app open.',
    done: "You've shown them the app working.",
  },
  {
    id: 'fix-1',
    day: '2026-10-27',
    tracks: ALL,
    tool: 'owners',
    title: 'Fix the top thing owners hit',
    what: 'Ask each owner what annoyed them most. Fix the top one.',
    done: 'The fix is live, and you told the owner.',
  },
  {
    id: 'fix-2',
    day: '2026-10-29',
    tracks: ALL,
    tool: 'owners',
    title: 'Fix the next thing',
    what: 'Fix the next thing owners hit, and keep them using it.',
    done: 'Owners are still using it today.',
  },
  {
    id: 'final',
    day: '2026-10-30',
    tracks: ALL,
    tool: 'owners',
    title: 'Send your final numbers',
    what: 'How many owners use it now, and what they did with it this week.',
    done: 'Numbers sent by the end of the day.',
    input: {
      kind: 'text',
      label: 'Your final numbers',
      placeholder: '3 owners, 210 orders, used every day this week',
    },
  },
]

/** The stretch features an autonomous founder chooses 2 of. They can also propose their own. */
export const STRETCH = [
  { id: 'whatsapp-bot', label: 'A WhatsApp bot that takes orders' },
  { id: 'voice', label: 'Voice-note orders in Hindi or Kannada' },
  { id: 'reply-agent', label: 'An AI agent that drafts replies to customers' },
  { id: 'forecast', label: 'A demand forecast' },
  { id: 'offline', label: 'Works offline, and syncs later' },
  { id: 'gst', label: 'GST invoice PDFs' },
  { id: 'languages', label: 'The app in more than one language' },
] as const

/**
 * What each stop asks for, per track. Fields marked `from` start filled with
 * the answer to that step, so a founder who kept up only checks and sends.
 */
export const STOP_FIELDS: StopField[] = [
  // Stop 1 · Fri 16 Oct
  {
    id: 'repo',
    stop: 1,
    tracks: ALL,
    kind: 'link',
    link: 'github',
    label: 'Your repo',
    from: ['g-card-1', 's-repo', 'a-repo'],
  },
  {
    id: 'live',
    stop: 1,
    tracks: ALL,
    kind: 'link',
    link: 'live',
    label: 'Your live link',
    from: ['g-card-3', 's-live', 'a-live'],
  },
  {
    id: 'design',
    stop: 1,
    tracks: ALL,
    kind: 'link',
    link: 'design',
    label: 'Your sketches or Figma',
    optional: true,
    from: ['sketch'],
  },
  {
    id: 'firstScreen',
    stop: 1,
    tracks: G,
    kind: 'text',
    label: 'Which screen did you build first, and why that one?',
  },
  {
    id: 'examples',
    stop: 1,
    tracks: S,
    kind: 'number',
    label: 'How many of your 10 real examples work?',
    from: ['s-examples'],
  },
  {
    id: 'arch',
    stop: 1,
    tracks: A,
    kind: 'link',
    link: 'doc',
    label: 'Your architecture note',
    from: ['a-arch'],
  },
  {
    id: 'stretch',
    stop: 1,
    tracks: A,
    kind: 'stretch',
    label: 'Your 2 stretch features',
    from: ['a-stretch'],
  },

  // Stop 2 · Fri 23 Oct
  {
    id: 'live',
    stop: 2,
    tracks: ALL,
    kind: 'link',
    link: 'live',
    label: 'Your live link',
    from: ['g-card-3', 's-live', 'a-live'],
  },
  { id: 'signin', stop: 2, tracks: ALL, kind: 'check', label: 'Google sign-in works on it' },
  { id: 'realData', stop: 2, tracks: ALL, kind: 'check', label: 'It saves real data, not samples' },
  {
    id: 'does',
    stop: 2,
    tracks: ALL,
    kind: 'text',
    label: 'What can an owner do with it today?',
  },
  {
    id: 'accuracy',
    stop: 2,
    tracks: A,
    kind: 'number',
    label: 'How many of the 50 messages came out right?',
    from: ['a-accuracy'],
  },
  {
    id: 'stretchBuilt',
    stop: 2,
    tracks: A,
    kind: 'text',
    label: 'Which stretch feature shipped?',
  },
  {
    id: 'ai',
    stop: 2,
    tracks: ['guided', 'structured'],
    kind: 'text',
    label: 'Did you add AI? Where?',
    hint: "It's an extra, not a must.",
    optional: true,
  },

  // Stop 3 · Mon 26 Oct
  {
    id: 'live',
    stop: 3,
    tracks: ALL,
    kind: 'link',
    link: 'live',
    label: 'Your live link',
    from: ['g-card-3', 's-live', 'a-live'],
  },
  {
    id: 'repo',
    stop: 3,
    tracks: ALL,
    kind: 'link',
    link: 'github',
    label: 'Your repo, with the README case study',
    from: ['g-card-1', 's-repo', 'a-repo'],
  },
  {
    id: 'video',
    stop: 3,
    tracks: ALL,
    kind: 'link',
    link: 'video',
    label: 'Your 3-minute demo video',
    hint: 'YouTube, Loom or Drive. Anyone with the link must be able to watch it.',
    from: ['g-card-15', 'demo'],
  },
  { id: 'owners', stop: 3, tracks: ALL, kind: 'number', label: 'How many owners use it?' },
  {
    id: 'usage',
    stop: 3,
    tracks: ALL,
    kind: 'text',
    label: 'What did they do with it?',
    from: ['numbers'],
  },
]
