import 'server-only'
import type { PlanStep, StopField } from '@/lib/steps'

/**
 * The plan, step by step: what each founder does on each day of the sprint,
 * in their words. Written to docs/VOICE.md and held to the same copy lint as
 * content/copy.ts. Server only, because each step names the tracks it's for,
 * and track names never reach a founder's browser.
 *
 * Step IDs are frozen once founders can tick them. Change the words freely;
 * never reuse an ID for a different step.
 *
 * The challenge is P045: help a kirana keep its loyal households ordering
 * from it rather than from the nearest dark store. No step names a solution:
 * finding one is the founder's work. Steps set the scope and the order.
 */

const G = ['guided'] as const
const S = ['structured'] as const
const A = ['autonomous'] as const
const SA = ['structured', 'autonomous'] as const
const ALL = ['guided', 'structured', 'autonomous'] as const

export const PLAN_STEPS: PlanStep[] = [
  // Fri 9 and Sat 10 Oct · research
  {
    id: 'r-talk',
    day: '2026-10-09',
    tracks: ALL,
    tool: 'owners',
    title: 'Talk to kirana owners and their regulars',
    what: 'Copy the research template into a Google Doc. Talk to 3 owners, and 3 regulars who also order from Blinkit, Zepto or Swiggy Instamart.',
    done: "Your doc holds what each of them told you, and what a kirana has that dark stores lack.",
  },
  {
    id: 'r-send',
    day: '2026-10-10',
    tracks: ALL,
    title: "Get your mentor's yes, then send it",
    what: 'Show your mentor the doc. Once they approve it, add the link and send your research. Your build days open.',
    done: 'Research sent before Sun 11 Oct.',
    input: { kind: 'research' },
  },

  // Week 1 · Sun 11 Oct · from research to your solution
  {
    id: 'solution',
    day: '2026-10-11',
    tracks: ALL,
    tool: 'claude',
    title: 'Write your solution in one line',
    what: 'Finish this in your doc: [which kirana owners] lose [what] when [which moment]. I will build [your idea] so that [what changes].',
    done: 'Your mentor agrees it follows from what you found.',
  },
  {
    id: 'unique',
    day: '2026-10-11',
    tracks: ALL,
    tool: 'claude',
    title: 'Make sure yours is not the obvious answer',
    what: '116 others have the same problem. Write down the answer most of them will build, then why yours is different.',
    done: 'Your mentor agrees yours is not the obvious one.',
    input: {
      kind: 'text',
      label: 'What makes yours different?',
      placeholder: 'Most will build ... Mine is different because ...',
    },
  },
  {
    id: 'g-flow',
    day: '2026-10-11',
    tracks: G,
    tool: 'claude',
    title: "Choose the one flow you'll build",
    what: 'Pick the single flow your solution cannot work without. Write it as 3 to 5 steps a person takes.',
    done: 'You can say it in one line: who does what, and what changes for the kirana.',
  },
  {
    id: 's-flows',
    day: '2026-10-11',
    tracks: S,
    tool: 'claude',
    title: 'Choose 2 or 3 flows that connect',
    what: 'Ask Claude to turn your solution into flows. Keep the 2 or 3 that matter most to the owner.',
    done: 'Each flow fits in one line, and you can say how they connect.',
  },
  {
    id: 'a-product',
    day: '2026-10-11',
    tracks: A,
    tool: 'claude',
    title: 'Shape a product, not a project',
    what: "Decide what the AI does that a form can't, who pays, and how a new shop finds you. Then plan the website and the app.",
    done: 'One page: the product, the AI at its centre, the website and the app.',
  },
  {
    id: 'sketch',
    day: '2026-10-11',
    tracks: ALL,
    tool: 'figma',
    title: 'Sketch every screen',
    what: 'Paper is fine. Use Figma if you like designing first. Draw one box per screen, with arrows between them.',
    done: 'A photo or Figma link with every screen in your flow.',
    input: { kind: 'link', link: 'design', label: 'Link to your sketch or Figma', optional: true },
  },

  // Mon 12 Oct · your repo
  {
    id: 'g-card-1',
    day: '2026-10-12',
    tracks: G,
    tool: 'github',
    card: 1,
    title: 'Make your own copy of the starter',
    what: 'Make a GitHub account, then make your own copy of the ForgeX starter. Card 1 shows every click.',
    done: 'You have a repo at github.com/your-name/your-repo.',
    input: { kind: 'link', link: 'github', label: 'Your repo link' },
  },
  {
    id: 's-repo',
    day: '2026-10-12',
    tracks: S,
    tool: 'github',
    title: 'Create your repo',
    what: "Start from the ForgeX starter, or a fresh Next.js app if you'd rather. It lives in your own GitHub.",
    done: 'Your repo exists, with a first commit.',
    input: { kind: 'link', link: 'github', label: 'Your repo link' },
  },
  {
    id: 's-system',
    day: '2026-10-12',
    tracks: S,
    tool: 'figma',
    title: 'Make a small design system',
    what: 'Pick 2 colours, 1 font, and how a button, a field and a card look. Use them everywhere.',
    done: 'One page in Figma, or one file in your code, that every screen follows.',
  },
  {
    id: 'a-repo',
    day: '2026-10-12',
    tracks: A,
    tool: 'supabase',
    title: 'Repo, database and tables',
    what: 'Create the repo and a Supabase project. Write the tables your product needs, with row-level security from day 1.',
    done: 'The tables exist, and a test row saves and reads back.',
    input: { kind: 'link', link: 'github', label: 'Your repo link' },
  },
  {
    id: 'a-arch',
    day: '2026-10-12',
    tracks: A,
    tool: 'claude',
    title: 'Write your architecture note',
    what: "One page: screens, tables, where AI sits, and what you'll fake for now. Put it in your repo as ARCHITECTURE.md.",
    done: 'The note is in your repo, and a stranger could follow it.',
    input: { kind: 'link', link: 'doc', label: 'Link to the note' },
  },
  {
    id: 'a-brand',
    day: '2026-10-12',
    tracks: A,
    tool: 'figma',
    title: 'Name it, and design the brand',
    what: 'Give the product a name, a logo mark and a voice. Use them on both the website and the app.',
    done: 'One page in Figma with the name, logo, colours and type.',
  },

  // Tue 13 Oct · Cursor and GitHub Copilot session
  {
    id: 'g-card-2',
    day: '2026-10-13',
    tracks: G,
    tool: 'cursor',
    card: 2,
    title: 'Run it on your laptop with Cursor',
    what: "Open your repo in Cursor and run it. Today's session walks you through it.",
    done: 'localhost:3000 shows the starter on your laptop.',
  },
  {
    id: 's-screens',
    day: '2026-10-13',
    tracks: S,
    tool: 'cursor',
    title: 'Code every screen with sample data',
    what: 'Build each screen in your flows with made-up data kept in one file. No database yet.',
    done: 'You can click through every screen on your laptop.',
  },
  {
    id: 'a-core',
    day: '2026-10-13',
    tracks: A,
    tool: 'cursor',
    title: 'Get the core flow working',
    what: 'One full path through the product, saving to Supabase. Rough is fine.',
    done: "You can do the main thing end to end, and it's saved.",
  },

  // Wed 14 Oct · go live
  {
    id: 'g-card-3',
    day: '2026-10-14',
    tracks: G,
    tool: 'vercel',
    card: 3,
    title: 'Go live on Vercel',
    what: 'Import your repo into Vercel. The setup screen is fine for now.',
    done: 'Your own link opens on your phone.',
    input: { kind: 'link', link: 'live', label: 'Your live link' },
  },
  {
    id: 's-live',
    day: '2026-10-14',
    tracks: S,
    tool: 'vercel',
    title: 'Go live on Vercel',
    what: 'Import your repo into Vercel. From now on, every push to GitHub updates your link.',
    done: 'Your link opens on your phone.',
    input: { kind: 'link', link: 'live', label: 'Your live link' },
  },
  {
    id: 'a-ai',
    day: '2026-10-14',
    tracks: A,
    tool: 'claude',
    title: 'AI does its one job on real input',
    what: "Use the Claude API, or a free Gemini key if you don't have one. Give it real input from your research.",
    done: 'Real input goes in, and the right result is saved.',
  },
  {
    id: 'a-landing',
    day: '2026-10-14',
    tracks: A,
    tool: 'vercel',
    title: 'Put up your website',
    what: "A full website, apart from the app. Cover the problem, your solution, how it works and who it's for. Add a waitlist that saves every sign-up.",
    done: 'The website is live, and its waitlist works.',
    input: { kind: 'link', link: 'live', label: 'Your website link' },
  },

  {
    id: 's-site-1',
    day: '2026-10-14',
    tracks: S,
    tool: 'vercel',
    title: 'Put up your website',
    what: "A website, apart from the app, in 4 or 5 sections. Cover the problem, your solution, how it works, who it's for, and owners' questions.",
    done: 'Your website is live and reads well on a phone.',
    input: { kind: 'link', link: 'live', label: 'Your website link' },
  },

  // Thu 15 Oct
  {
    id: 'g-card-4',
    day: '2026-10-15',
    tracks: G,
    tool: 'cursor',
    card: 4,
    title: 'Make it yours: name, colours and words',
    what: 'Give it a name, your colours, and the words kirana owners actually use.',
    done: 'Your live link looks like your product, not the starter.',
  },
  {
    id: 'g-site-1',
    day: '2026-10-15',
    tracks: G,
    tool: 'vercel',
    title: 'Put up your website',
    what: 'One page, apart from the app. Cover the problem in your words, your solution, how it works in 3 steps, and how to reach you.',
    done: 'Your website is live and reads well on a phone.',
    input: { kind: 'link', link: 'live', label: 'Your website link' },
  },
  {
    id: 's-examples',
    day: '2026-10-15',
    tracks: S,
    tool: 'owners',
    title: 'Put 10 real cases through it',
    what: "Take 10 real situations from your research and run each one through your app. Note what doesn't fit.",
    done: "You know which of the 10 work, and why the rest don't.",
    input: { kind: 'number', label: 'How many of the 10 work?' },
  },
  {
    id: 'a-live',
    day: '2026-10-15',
    tracks: A,
    tool: 'vercel',
    title: 'Go live on Vercel',
    what: 'Import your repo into Vercel and add your keys as environment variables.',
    done: 'The core flow works on your live link.',
    input: { kind: 'link', link: 'live', label: 'Your live link' },
  },
  {
    id: 'a-stretch',
    day: '2026-10-15',
    tracks: A,
    title: 'Propose 2 stretch features',
    what: 'Beyond your core, propose 2 features. Tie each one to something your research found.',
    done: 'Your mentor agrees both are worth the time.',
    input: {
      kind: 'text',
      label: 'Your 2 stretch features, and why',
      placeholder: '1. A feature, because of what you found. 2. Another, and why.',
    },
  },

  // Fri 16 Oct · phase 1 due
  {
    id: 'g-card-5',
    day: '2026-10-16',
    tracks: G,
    tool: 'cursor',
    card: 5,
    title: 'Build the first screen of your flow',
    what: 'Use card 5 and the build-a-screen prompt. Sample data is fine. Check it on your phone.',
    done: 'The screen is on your live link.',
  },
  {
    id: 'stop-1',
    day: '2026-10-16',
    tracks: ALL,
    title: 'Send phase 1 by 6 pm',
    what: 'Your repo, your live link and your research go to the team. You can edit it until 6 pm.',
    done: 'Sent before 6 pm IST.',
    input: { kind: 'stop', stop: 1 },
  },

  // Sat 17 Oct · AI Sprint · Pitch day for phase 1
  {
    id: 'pitch',
    day: '2026-10-17',
    tracks: ALL,
    tool: 'owners',
    title: 'Pitch your MVP at AI Sprint',
    what: "3 minutes: who it's for, what you found, your solution, then the live link on your phone.",
    done: "You've pitched, and you know what to change next.",
  },

  // Week 2 · Sun 18 Oct
  {
    id: 'g-card-6',
    day: '2026-10-18',
    tracks: G,
    tool: 'cursor',
    card: 6,
    title: 'Turn your flow into data',
    what: 'List what your flow needs to remember. Copy the example table for each thing.',
    done: 'Your tables are written down, with sample rows.',
  },
  {
    id: 'g-card-7',
    day: '2026-10-18',
    tracks: G,
    tool: 'cursor',
    card: 7,
    title: 'Build your core flow, part 1',
    what: 'Build the first steps of your flow on sample data. Card 7 has the prompt to fill in.',
    done: 'The first half of your flow works on your laptop.',
  },
  {
    id: 's-stretch',
    day: '2026-10-18',
    tracks: S,
    title: 'Propose 1 stretch feature',
    what: 'After the pitch, propose 1 feature beyond your flows. Tie it to something your research or the pitch feedback showed.',
    done: 'Your mentor agrees it is worth the time.',
    input: {
      kind: 'text',
      label: 'Your stretch feature, and why',
      placeholder: 'A feature, because of what you found.',
    },
  },
  {
    id: 's-flow-2',
    day: '2026-10-18',
    tracks: S,
    tool: 'cursor',
    title: 'Build your second flow',
    what: 'Build the next flow you chose, on sample data. Link it to the first.',
    done: 'You can move from one flow to the other without a dead end.',
  },
  {
    id: 'a-many',
    day: '2026-10-18',
    tracks: A,
    tool: 'supabase',
    title: 'Many shops, each sees only its own',
    what: "Make shops a table and lock every query to the signed-in owner's shop with row-level security.",
    done: "Sign in as 2 owners. Neither can see the other's data.",
  },
  {
    id: 'a-agent',
    day: '2026-10-18',
    tracks: A,
    tool: 'claude',
    title: 'An AI agent that acts, once approved',
    what: 'Let your AI take one real action on its own, not just answer. A person approves it before it happens.',
    done: 'The agent proposes an action, a person approves, and it happens.',
  },

  // Mon 19 Oct
  {
    id: 'g-card-8',
    day: '2026-10-19',
    tracks: G,
    tool: 'cursor',
    card: 8,
    title: 'Build your core flow, part 2',
    what: 'Finish your flow, end to end, on sample data.',
    done: 'Someone can do your whole flow on your live link.',
  },
  {
    id: 's-db',
    day: '2026-10-19',
    tracks: S,
    tool: 'supabase',
    title: 'Save to a real database',
    what: "Follow the Supabase steps in the starter's README. Wednesday's session covers it if you get stuck.",
    done: 'What you enter is still there after a refresh.',
  },
  {
    id: 'a-pay',
    day: '2026-10-19',
    tracks: A,
    title: 'Subscriptions in test mode',
    what: 'Add a paid plan with Razorpay or Stripe in test mode. A shop can subscribe, and your app knows it did.',
    done: 'A test subscription goes through and unlocks the plan.',
  },
  {
    id: 'g-owner',
    day: '2026-10-19',
    tracks: G,
    tool: 'owners',
    title: "Find the owner who'll use it",
    what: "Ask a kirana owner you spoke to if they'll try it from Saturday. Get a yes and a time.",
    done: '1 owner has said yes.',
  },
  {
    id: 's-owners',
    day: '2026-10-19',
    tracks: S,
    tool: 'owners',
    title: 'Get 3 kirana owners to say yes',
    what: 'Ask 3 owners to use it for a week. Show the first one what you have, even on sample data.',
    done: '3 owners have said yes, and 1 has seen it.',
  },
  {
    id: 'a-owners',
    day: '2026-10-19',
    tracks: A,
    tool: 'owners',
    title: 'Line up 5 or more kirana owners',
    what: 'Ask 5 owners to use it from Saturday. Start the first one now.',
    done: '5 owners have said yes, and 1 is already using it.',
  },

  {
    id: 's-testimonials',
    day: '2026-10-19',
    tracks: S,
    tool: 'owners',
    title: 'Record 4 video testimonials',
    what: '2 kirana owners, and 2 households who switched to Blinkit, Zepto or Swiggy Instamart. 30 seconds each, on a phone, with their permission.',
    done: '4 short videos, each person saying it in their own words.',
  },
  {
    id: 'a-testimonials',
    day: '2026-10-19',
    tracks: A,
    tool: 'owners',
    title: 'Record 6 video testimonials',
    what: '3 kirana owners, and 3 households who switched to Blinkit, Zepto or Swiggy Instamart. 30 seconds each, with their permission.',
    done: '6 short videos, each person saying it in their own words.',
  },

  // Tue 20 Oct
  {
    id: 'g-card-9',
    day: '2026-10-20',
    tracks: G,
    tool: 'cursor',
    card: 9,
    title: 'The screen your user opens every day',
    what: 'Decide what your user needs to see first, every day, and build that screen.',
    done: 'It shows what matters to them, and fits on a phone.',
  },
  {
    id: 's-view',
    day: '2026-10-20',
    tracks: S,
    tool: 'cursor',
    title: "The owner's daily view",
    what: 'One screen the owner opens every morning, built from what your research says matters to them.',
    done: 'The view uses your real data and fits on a phone.',
  },
  {
    id: 'a-stretch-1',
    day: '2026-10-20',
    tracks: A,
    tool: 'cursor',
    title: 'Build stretch feature 1',
    what: 'Build the first stretch feature you proposed. Ship a small version today.',
    done: 'It works on your live link, end to end.',
  },
  {
    id: 'a-messages',
    day: '2026-10-20',
    tracks: A,
    tool: 'owners',
    title: 'Collect 50 real inputs',
    what: 'Gather 50 real examples from your owners, each with the answer your AI should give.',
    done: '50 examples, each with the right answer written next to it.',
  },
  {
    id: 'a-channel',
    day: '2026-10-20',
    tracks: A,
    title: 'Reach people beyond the browser',
    what: 'Add one more channel your users already live in: chat, voice or SMS. Your research says which.',
    done: 'Someone can use your product without opening the app.',
  },

  {
    id: 'g-testimonials',
    day: '2026-10-20',
    tracks: G,
    tool: 'owners',
    title: 'Record 2 video testimonials',
    what: '1 kirana owner, and 1 household who switched to Blinkit, Zepto or Swiggy Instamart. 30 seconds each, on a phone, with their permission.',
    done: '2 short videos, each person saying it in their own words.',
  },

  // Wed 21 Oct · Google Cloud and Supabase session
  {
    id: 'g-card-10',
    day: '2026-10-21',
    tracks: G,
    tool: 'supabase',
    card: 10,
    title: 'Connect Supabase and Google sign-in',
    what: "Follow card 10 in today's session. You'll paste 2 keys and run 1 file.",
    done: 'You sign in with Google on your live link, and your data saves.',
  },
  {
    id: 's-signin',
    day: '2026-10-21',
    tracks: S,
    tool: 'gcloud',
    title: 'Google sign-in and a second role',
    what: 'Add Google sign-in, then a second role that sees less than the owner does.',
    done: 'The owner and the second role see different things.',
  },
  {
    id: 'a-monitor',
    day: '2026-10-21',
    tracks: A,
    title: 'Error monitoring',
    what: "Add error monitoring, such as Sentry's free plan. You hear about a crash before the owner does.",
    done: 'A test error shows up in your monitoring.',
  },
  {
    id: 'a-ci',
    day: '2026-10-21',
    tracks: A,
    tool: 'github',
    title: 'Tests that run on every push',
    what: 'Set up GitHub Actions to run your tests and your AI checks on every push.',
    done: 'A broken change shows a red check on GitHub before it goes live.',
  },

  // Thu 22 Oct
  {
    id: 'g-card-11',
    day: '2026-10-22',
    tracks: G,
    tool: 'owners',
    card: 11,
    title: 'Real data from one owner',
    what: 'Sit with one kirana owner and put a real day into it, together.',
    done: 'Real data is in your app, not sample rows.',
  },
  {
    id: 's-upi',
    day: '2026-10-22',
    tracks: S,
    tool: 'cursor',
    title: 'Take a payment, in test mode',
    what: 'Wherever money moves in your solution, add a UPI link or Razorpay in test mode.',
    done: 'A test payment goes through, with the right amount.',
  },
  {
    id: 's-tests',
    day: '2026-10-22',
    tracks: S,
    tool: 'copilot',
    title: 'Write tests for what people trust',
    what: 'Ask Copilot to write tests for the sums and rules your users rely on.',
    done: 'The tests pass, and fail when a rule breaks.',
  },
  {
    id: 'a-accuracy',
    day: '2026-10-22',
    tracks: A,
    tool: 'claude',
    title: 'Measure your AI on 50 real inputs',
    what: 'Run all 50 examples through your AI and count how many come out right.',
    done: 'You have one number, and a list of what it got wrong.',
    input: { kind: 'number', label: 'How many of the 50 came out right?' },
  },
  {
    id: 'a-analytics',
    day: '2026-10-22',
    tracks: A,
    title: 'Know what owners actually do',
    what: "Add product analytics, such as PostHog's free plan. Track the 3 actions that prove your product works.",
    done: 'You can see each of the 3 actions, counted, by day.',
  },

  {
    id: 'g-site-2',
    day: '2026-10-22',
    tracks: G,
    tool: 'vercel',
    title: 'Website, version 2',
    what: 'Add your 2 testimonials and real screenshots of your app.',
    done: 'Someone could understand your product from the website alone.',
  },
  {
    id: 's-site-2',
    day: '2026-10-22',
    tracks: S,
    tool: 'vercel',
    title: 'Website, version 2',
    what: "Add your 4 testimonials, a features section, and how you'd charge owners.",
    done: 'Someone could understand your product, and its price, from the website alone.',
  },
  {
    id: 'a-site-2',
    day: '2026-10-22',
    tracks: A,
    tool: 'vercel',
    title: 'Website, version 2',
    what: 'Add your 6 testimonials, features, pricing, and a sign-up that leads straight into the app.',
    done: 'A stranger can go from your website to using the app, alone.',
  },

  // Fri 23 Oct · Vercel session · phase 2 due
  {
    id: 'g-card-12',
    day: '2026-10-23',
    tracks: G,
    card: 12,
    title: 'Check every screen on your phone',
    what: 'Open each screen on your phone and fix anything you have to pinch or zoom.',
    done: 'Every screen works one-handed on a phone.',
  },
  {
    id: 'phone',
    day: '2026-10-23',
    tracks: SA,
    title: 'Check every screen on your phone',
    what: 'Open each screen on your phone and fix anything you have to pinch or zoom.',
    done: 'Every screen works one-handed on a phone.',
  },
  {
    id: 'stop-2',
    day: '2026-10-23',
    tracks: ALL,
    title: 'Send phase 2 by 6 pm',
    what: 'Your live link, with Google sign-in and real data. You can edit it until 6 pm.',
    done: 'Sent before 6 pm IST.',
    input: { kind: 'stop', stop: 2 },
  },

  // Week 3 · Sat 24 Oct · real owners
  {
    id: 'g-card-13',
    day: '2026-10-24',
    tracks: G,
    tool: 'owners',
    card: 13,
    title: "Put it in your owner's hands",
    what: 'Set it up on their phone and watch them use it for real.',
    done: 'Your owner has used it with real households.',
  },
  {
    id: 's-users',
    day: '2026-10-24',
    tracks: S,
    tool: 'owners',
    title: '3 owners using it',
    what: "Set it up on each owner's phone. Check in with each one every day.",
    done: '3 owners use it for real this week.',
  },
  {
    id: 's-stretch-1',
    day: '2026-10-24',
    tracks: S,
    tool: 'cursor',
    title: 'Build your stretch feature',
    what: 'Build the stretch feature you proposed, sized to ship before phase 3.',
    done: 'It works on your live link, end to end.',
  },
  {
    id: 'a-users',
    day: '2026-10-24',
    tracks: A,
    tool: 'owners',
    title: '5 or more owners using it',
    what: 'Set it up with each owner and log what they do each day.',
    done: '5 owners use it, and you can see their numbers.',
  },
  {
    id: 'a-stretch-2',
    day: '2026-10-24',
    tracks: A,
    tool: 'cursor',
    title: 'Build stretch feature 2',
    what: 'Build the second stretch feature, sized to ship in 2 days.',
    done: 'It works on your live link, end to end.',
  },

  {
    id: 'a-onboard',
    day: '2026-10-24',
    tracks: A,
    title: 'A new shop starts alone, in 5 minutes',
    what: 'A new owner signs up from your website and is set up without you on the call.',
    done: 'Someone you have never met set it up alone in 5 minutes.',
  },

  // Sun 25 Oct
  {
    id: 'g-card-14',
    day: '2026-10-25',
    tracks: G,
    tool: 'github',
    card: 14,
    title: 'Write the README case study',
    what: "Who it's for, what you found, what you built, and the numbers. Add screenshots from a phone.",
    done: 'Someone outside Mesa could read it and understand your work.',
  },
  {
    id: 'readme',
    day: '2026-10-25',
    tracks: SA,
    tool: 'github',
    title: 'Write the README case study',
    what: "Who it's for, what you found, what you built, and the numbers. Add screenshots from a phone.",
    done: 'Someone outside Mesa could read it and understand your work.',
  },
  {
    id: 'site-3',
    day: '2026-10-25',
    tracks: ALL,
    tool: 'vercel',
    title: 'Website, version 3: the results',
    what: 'Add what changed for real owners: your numbers, their words, and your Loom.',
    done: 'Your website shows proof, not promises.',
  },
  {
    id: 'numbers',
    day: '2026-10-25',
    tracks: ALL,
    tool: 'owners',
    title: 'Count the usage',
    what: 'Count what owners did with it: how often, how many households, and what changed.',
    done: 'You have numbers you can say out loud in the demo.',
    input: {
      kind: 'text',
      label: 'Your numbers',
      placeholder: '2 owners, 40 households, used every day for 3 days',
    },
  },

  // Mon 26 Oct · phase 3 due
  {
    id: 'g-card-15',
    day: '2026-10-26',
    tracks: G,
    card: 15,
    title: 'Record the 3-minute demo on Loom',
    what: "Record it on Loom, on your phone, using the real app. Show your owner's real use.",
    done: 'A 3-minute Loom link that anyone can open.',
    input: { kind: 'link', link: 'video', label: 'Your Loom link' },
  },
  {
    id: 'demo',
    day: '2026-10-26',
    tracks: SA,
    title: 'Record the 3-minute demo on Loom',
    what: "Record it on Loom, on your phone, using the real app. Show real owners' use.",
    done: 'A 3-minute Loom link that anyone can open.',
    input: { kind: 'link', link: 'video', label: 'Your Loom link' },
  },
  {
    id: 'producthunt',
    day: '2026-10-26',
    tracks: ALL,
    title: 'Launch on Product Hunt',
    what: 'Publish your product on Product Hunt by Mon 26 Oct, with your Loom and live link. Share it with your owners and the cohort.',
    done: 'Your product is live on Product Hunt.',
    input: { kind: 'link', link: 'producthunt', label: 'Your Product Hunt link' },
  },
  {
    id: 'stop-3',
    day: '2026-10-26',
    tracks: ALL,
    title: 'Send phase 3 by 6 pm',
    what: 'Your demo, your README and your numbers go to the team. You can edit it until 6 pm.',
    done: 'Sent before 6 pm IST.',
    input: { kind: 'stop', stop: 3 },
  },

  // Tue 27 to Fri 30 Oct · keep building, and check-ins
  {
    id: 'checkin',
    day: '2026-10-27',
    tracks: ALL,
    title: 'Your check-in with the team',
    what: 'Pragati and Chandu meet each of you this week. Bring your phone, with the app open.',
    done: "You've shown them the app working.",
  },
  {
    id: 'fix-1',
    day: '2026-10-27',
    tracks: ALL,
    tool: 'owners',
    title: 'Fix the top thing owners hit',
    what: 'Ask each owner what annoyed them most. Fix the top one.',
    done: 'The fix is live, and you told the owner.',
  },
  {
    id: 'fix-2',
    day: '2026-10-29',
    tracks: ALL,
    tool: 'owners',
    title: 'Fix the next thing',
    what: 'Fix the next thing owners hit, and keep them using it.',
    done: 'Owners are still using it today.',
  },
  {
    id: 'final',
    day: '2026-10-30',
    tracks: ALL,
    tool: 'owners',
    title: 'Send your final numbers',
    what: 'How many owners use it now, and what they did with it this week.',
    done: 'Numbers sent by the end of the day.',
    input: {
      kind: 'text',
      label: 'Your final numbers',
      placeholder: '3 owners, 120 households, used every day this week',
    },
  },
]

/** Stretch features are the founder's own proposals now; no list is offered, so none is suggested. */
export const STRETCH: readonly { id: string; label: string }[] = []

/**
 * What each stop asks for, per track. Fields marked `from` start filled with
 * the answer to that step, so a founder who kept up only checks and sends.
 */
export const STOP_FIELDS: StopField[] = [
  // Stop 1 · Fri 16 Oct
  {
    id: 'repo',
    stop: 1,
    tracks: ALL,
    kind: 'link',
    link: 'github',
    label: 'Your repo',
    from: ['g-card-1', 's-repo', 'a-repo'],
  },
  {
    id: 'live',
    stop: 1,
    tracks: ALL,
    kind: 'link',
    link: 'live',
    label: 'Your live link',
    from: ['g-card-3', 's-live', 'a-live'],
  },
  {
    id: 'design',
    stop: 1,
    tracks: ALL,
    kind: 'link',
    link: 'design',
    label: 'Your sketches or Figma',
    optional: true,
    from: ['sketch'],
  },
  {
    id: 'firstScreen',
    stop: 1,
    tracks: G,
    kind: 'text',
    label: 'Which screen did you build first, and why that one?',
  },
  {
    id: 'examples',
    stop: 1,
    tracks: S,
    kind: 'number',
    label: 'How many of your 10 real cases work?',
    from: ['s-examples'],
  },
  {
    id: 'arch',
    stop: 1,
    tracks: A,
    kind: 'link',
    link: 'doc',
    label: 'Your architecture note',
    from: ['a-arch'],
  },
  {
    id: 'website',
    stop: 1,
    tracks: ALL,
    kind: 'link',
    link: 'live',
    label: 'Your website: the problem and your solution',
    from: ['g-site-1', 's-site-1', 'a-landing'],
  },
  {
    id: 'different',
    stop: 1,
    tracks: ALL,
    kind: 'text',
    label: 'What makes your solution different?',
    from: ['unique'],
  },
  {
    id: 'stretch',
    stop: 1,
    tracks: A,
    kind: 'text',
    label: 'Your 2 stretch features, and why',
    from: ['a-stretch'],
  },

  // Stop 2 · Fri 23 Oct
  {
    id: 'live',
    stop: 2,
    tracks: ALL,
    kind: 'link',
    link: 'live',
    label: 'Your live link',
    from: ['g-card-3', 's-live', 'a-live'],
  },
  {
    id: 'website',
    stop: 2,
    tracks: ALL,
    kind: 'link',
    link: 'live',
    label: 'Your website, with testimonials',
    from: ['g-site-1', 's-site-1', 'a-landing'],
  },
  {
    id: 'testimonials',
    stop: 2,
    tracks: ALL,
    kind: 'number',
    label: 'How many video testimonials are on it?',
  },
  { id: 'signin', stop: 2, tracks: ALL, kind: 'check', label: 'Google sign-in works on it' },
  { id: 'realData', stop: 2, tracks: ALL, kind: 'check', label: 'It saves real data, not samples' },
  {
    id: 'does',
    stop: 2,
    tracks: ALL,
    kind: 'text',
    label: 'What can an owner do with it today?',
  },
  {
    id: 'accuracy',
    stop: 2,
    tracks: A,
    kind: 'number',
    label: 'How many of the 50 real inputs came out right?',
    from: ['a-accuracy'],
  },
  {
    id: 'stretchBuilt',
    stop: 2,
    tracks: A,
    kind: 'text',
    label: 'Which stretch feature shipped?',
  },
  {
    id: 'ai',
    stop: 2,
    tracks: ['guided', 'structured'],
    kind: 'text',
    label: 'Did you add AI? Where?',
    hint: "It's an extra, not a must.",
    optional: true,
  },

  // Stop 3 · Mon 26 Oct
  {
    id: 'live',
    stop: 3,
    tracks: ALL,
    kind: 'link',
    link: 'live',
    label: 'Your live link',
    from: ['g-card-3', 's-live', 'a-live'],
  },
  {
    id: 'repo',
    stop: 3,
    tracks: ALL,
    kind: 'link',
    link: 'github',
    label: 'Your repo, with the README case study',
    from: ['g-card-1', 's-repo', 'a-repo'],
  },
  {
    id: 'video',
    stop: 3,
    tracks: ALL,
    kind: 'link',
    link: 'video',
    label: 'Your 3-minute Loom video',
    hint: 'Record it on Loom and paste the share link. Anyone with the link must be able to watch it.',
    from: ['g-card-15', 'demo'],
  },
  {
    id: 'website',
    stop: 3,
    tracks: ALL,
    kind: 'link',
    link: 'live',
    label: 'Your website, with the results',
    from: ['g-site-1', 's-site-1', 'a-landing'],
  },
  {
    id: 'stretchBuilt',
    stop: 3,
    tracks: S,
    kind: 'text',
    label: 'Which stretch feature shipped?',
  },
  {
    id: 'producthunt',
    stop: 3,
    tracks: ALL,
    kind: 'link',
    link: 'producthunt',
    label: 'Your Product Hunt link',
    from: ['producthunt'],
  },
  { id: 'owners', stop: 3, tracks: ALL, kind: 'number', label: 'How many owners use it?' },
  {
    id: 'usage',
    stop: 3,
    tracks: ALL,
    kind: 'text',
    label: 'What did they do with it?',
    from: ['numbers'],
  },
]
